//TYPES OF VALUES

let lastName = 'Sendid'; //String (Chaine de Caractères) 
let firstName = 'Ismail'; //String
let revenues = 23000; //Number
let expenses = 13000;
let profit = revenues - expenses;
let isIsmailFasting = true; //Boolean
let money; //Undefined
console.log(lastName);
console.log(firstName);
console.log('The money Generated by ' + lastName + ' ' + firstName + ' is ' + profit);
console.log(`The money Generated by ${lastName} ${firstName} is ${profit}`);
console.log(typeof money);
